### ISSUE TITLE
Creating channels sometimes causes errors

### ISSUE THREAD

**Issue by luisdemarchi** [wenxin3262/WebRTC-iOS#2]
I have a method to create channel that occasionally causes an error and closes the app.

```
func createDataChannels() throws {
        self.chatChannel?.close()
        
        let channelConfig = RTCDataChannelConfiguration()
        channelConfig.isNegotiated = true
        channelConfig.isOrdered = true
        channelConfig.maxRetransmits = 30
        
        self.chatChannel?.close()
        channelConfig.channelId = 1
        **self.chatChannel = peer?.dataChannel(forLabel: "chat", configuration: channelConfig)**
        self.chatChannel?.delegate = self
}
```

> 2017-02-12 00:52:24.482 WebRTCDemo[560:105756] *** Assertion failure in -[RTCDataChannel initWithNativeDataChannel:], ../../webrtc/sdk/objc/Framework/Classes/RTCDataChannel.mm:170
> 2017-02-12 00:52:24.484 WebRTCDemo[560:105756] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: nativeDataChannel'
> *** First throw call stack:
> (0x22d0391b 0x2249ee17 0x22d037f1 0x234e7529 0x2f4b6d 0x2fb1c1 0x45124 0x45428 0x3cfe8 0x3df10 0x423d0 0x37db8 0x233c68 0x237040 0x2307d0 0x1016e39 0x1009b6b 0x100e655 0x22cc5b6d 0x22cc4067 0x22c13229 0x22c13015 0x24203ac9 0x272e7189 0x48edc 0x228bb873)
> libc++abi.dylib: terminating with uncaught exception of type NSException
> warning: could not load any Objective-C class information. This will significantly reduce the quality of type information available.

**Comment by wenxin3262** [comment]
If you believe this is a bug in webrtc, please report to them. This framework is unmodified and directly compiled from the source. I haven't worked on any datachannel features so I don't know. For chat in iOS specifically, I would suggest you take a look at firebase or socket.io.
