### ISSUE TITLE
Enable H264 video

### ISSUE THREAD

**Issue by luisdemarchi** [wenxin3262/WebRTC-iOS#3]
I'm reading in many places that to activate the video in H264 just activate a flag and recompile the version of webRTC. But I'm using your library for this "bridge".

Is it possible for you to activate this flag? Or indicate the path of the stones?
(Flag use_objc_h264)

**Comment by wenxin3262** [comment]
Hi, for this project I only run the script from WebRTC org with default configurations. If you have time you are welcome to pr.
