### ISSUE TITLE
webrtc  sdp connection failed

### ISSUE THREAD

**Issue by Tony-Day** [wenxin3262/WebRTC-iOS#6]
device: iPhone XR
iOS Version: [iOS 12.3]
Xcode Version: [Xcode 10.3]

Two iPhone Xr Calls，If both phones use two phone cards, webrtc will not be able to connect.

**Comment by wenxin3262** [comment]
@BzHuang I can help if you have any questions related to the framework itself, for webrtc questions, please find help https://groups.google.com/forum/#!forum/discuss-webrtc
